server:
  port: ${API_GATEWAY_PORT:8500}
  
spring:
  profiles:
    active: default
  cloud:
    config:
      enabled: true
      uri: ${CONFIG_SERVER_URL:http://localhost:8100}
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER_URL:http://localhost:8300}
        instance:
          prefer-ip: true
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8200}/eureka
      
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.usl.microservices: DEBUG 
    
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      enabled: true

ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true
    
