server:
  port: ${PAYMENT_SERVER_PORT:8900}

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
#      bindings:
#        catalog-lookup-in:
#          destination: CatelogLookupTopic
#          content-type: application/json
#          group: CatelogGroup
#        pricing-change-in:
#          destination: PricingChangeTopic
#          content-type: application/json
#          group: PricingGroup
#        catalog-lookup-out:
#          destination: CatelogLookupTopic
#          content-type: application/json
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411}
    discovery-client-enabled: true
    sender:
      type: kafka
    locator:
      discovery:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true
    
    